### ISSUE TITLE
Returns accumulated values when used in a matrix loop

### ISSUE THREAD

**Issue by cliveportman** [bransinanderson/Craft-Roman#1]
{% for block in entry.matrixField %}
     	{{ craft.roman.getRoman(loop.index) }}<br>
    {% endfor %}

returns something like:
I
III
IIIII
IIIIIIV
IIIIIIVV

I found this worked:

    function getRoman($number)
	    {
		    $this->result = ""; // prevents accumulated values
            foreach($this->romans as $key => $value)

**Comment by bransinanderson** [comment]
Thanks for reporting Clive! Fixed.
